
import java.util.*;

public class Test12 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(3, 78, "aaab"),
            new Cetrta.Prostor(5, 2, "baab"),
            new Cetrta.Prostor(7, 62, "bbab"),
            new Cetrta.Prostor(9, 32, "abba"),
            new Cetrta.Prostor(5, 96, "bbab"),
            new Cetrta.Prostor(2, 8, "aba"),
            new Cetrta.Prostor(6, 37, "aaab"),
            new Cetrta.Prostor(2, 45, "abba"),
            new Cetrta.Prostor(8, 89, "aaab"),
            new Cetrta.Prostor(1, 37, "aa"),
            new Cetrta.Prostor(9, 47, "aaab"),
            new Cetrta.Prostor(1, 39, "aa"),
            new Cetrta.Prostor(9, 95, "aaab"),
            new Cetrta.Prostor(4, 19, "baab"),
            new Cetrta.Prostor(6, 46, "aba"),
            new Cetrta.Prostor(7, 49, "aa"),
            new Cetrta.Prostor(8, 78, "bbab"),
            new Cetrta.Prostor(5, 20, "aba"),
            new Cetrta.Prostor(5, 98, "abba"),
            new Cetrta.Prostor(9, 15, "aba"),
            new Cetrta.Prostor(2, 98, "aa"),
            new Cetrta.Prostor(9, 4, "aaab"),
            new Cetrta.Prostor(6, 11, "aba"),
            new Cetrta.Prostor(2, 46, "aa"),
            new Cetrta.Prostor(7, 37, "aaab"),
            new Cetrta.Prostor(1, 81, "bbab"),
            new Cetrta.Prostor(8, 61, "baab"),
            new Cetrta.Prostor(1, 53, "aa"),
            new Cetrta.Prostor(5, 66, "abba"),
            new Cetrta.Prostor(5, 89, "abba"),
            new Cetrta.Prostor(5, 73, "aba"),
            new Cetrta.Prostor(2, 60, "baab"),
            new Cetrta.Prostor(9, 23, "aba"),
            new Cetrta.Prostor(1, 99, "aba"),
            new Cetrta.Prostor(1, 20, "aaab"),
            new Cetrta.Prostor(6, 69, "bbab"),
            new Cetrta.Prostor(3, 28, "aba"),
            new Cetrta.Prostor(1, 38, "baab"),
            new Cetrta.Prostor(7, 99, "baab"),
            new Cetrta.Prostor(7, 63, "aa"),
            new Cetrta.Prostor(5, 94, "aa"),
            new Cetrta.Prostor(3, 55, "aaab"),
            new Cetrta.Prostor(1, 44, "aba"),
            new Cetrta.Prostor(4, 3, "aba"),
            new Cetrta.Prostor(4, 80, "abba"),
            new Cetrta.Prostor(5, 45, "aba"),
            new Cetrta.Prostor(4, 39, "aaab"),
            new Cetrta.Prostor(7, 63, "aa"),
            new Cetrta.Prostor(3, 37, "aaab"),
            new Cetrta.Prostor(3, 30, "aaab"),
            new Cetrta.Prostor(3, 35, "bbab"),
            new Cetrta.Prostor(3, 44, "aaab"),
            new Cetrta.Prostor(4, 3, "aa"),
            new Cetrta.Prostor(6, 79, "abba"),
            new Cetrta.Prostor(7, 42, "abba"),
            new Cetrta.Prostor(6, 33, "baab"),
            new Cetrta.Prostor(1, 68, "aba"),
            new Cetrta.Prostor(1, 34, "aa"),
            new Cetrta.Prostor(8, 75, "aa"),
            new Cetrta.Prostor(5, 56, "aa"),
            new Cetrta.Prostor(7, 88, "aba"),
            new Cetrta.Prostor(8, 78, "aba"),
            new Cetrta.Prostor(3, 17, "aba"),
            new Cetrta.Prostor(8, 63, "aaab"),
            new Cetrta.Prostor(4, 65, "aba"),
            new Cetrta.Prostor(5, 13, "aba"),
            new Cetrta.Prostor(2, 100, "aa"),
            new Cetrta.Prostor(7, 72, "baab"),
            new Cetrta.Prostor(3, 52, "bbab"),
            new Cetrta.Prostor(1, 72, "aaab"),
            new Cetrta.Prostor(6, 36, "aa"),
            new Cetrta.Prostor(6, 10, "bbab"),
            new Cetrta.Prostor(2, 18, "bbab"),
            new Cetrta.Prostor(5, 100, "aa"),
            new Cetrta.Prostor(4, 1, "bbab"),
            new Cetrta.Prostor(7, 85, "aaab"),
            new Cetrta.Prostor(6, 92, "bbab"),
            new Cetrta.Prostor(2, 67, "aa"),
            new Cetrta.Prostor(3, 44, "abba"),
            new Cetrta.Prostor(1, 9, "baab"),
            new Cetrta.Prostor(1, 11, "abba"),
            new Cetrta.Prostor(9, 50, "aa"),
            new Cetrta.Prostor(1, 44, "abba"),
            new Cetrta.Prostor(7, 71, "aa"),
            new Cetrta.Prostor(1, 32, "aba"),
            new Cetrta.Prostor(5, 82, "abba"),
            new Cetrta.Prostor(7, 24, "aa"),
            new Cetrta.Prostor(5, 33, "bbab"),
            new Cetrta.Prostor(4, 27, "bbab"),
            new Cetrta.Prostor(6, 69, "aa"),
            new Cetrta.Prostor(9, 36, "aa"),
            new Cetrta.Prostor(1, 14, "aa"),
            new Cetrta.Prostor(2, 6, "aaab"),
            new Cetrta.Prostor(1, 91, "aaab"),
            new Cetrta.Prostor(1, 7, "aa"),
            new Cetrta.Prostor(8, 53, "aaab"),
            new Cetrta.Prostor(8, 19, "aa"),
            new Cetrta.Prostor(7, 33, "abba"),
            new Cetrta.Prostor(4, 84, "baab"),
            new Cetrta.Prostor(2, 61, "aa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
