
import java.util.*;

public class Test15 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(7, 78, "baaba"),
            new Cetrta.Prostor(9, 7, "bb"),
            new Cetrta.Prostor(8, 97, "aa"),
            new Cetrta.Prostor(7, 76, "baba"),
            new Cetrta.Prostor(7, 45, "abbbb"),
            new Cetrta.Prostor(2, 6, "bb"),
            new Cetrta.Prostor(5, 77, "baba"),
            new Cetrta.Prostor(2, 77, "baaba"),
            new Cetrta.Prostor(3, 48, "bb"),
            new Cetrta.Prostor(7, 92, "abbbb"),
            new Cetrta.Prostor(4, 39, "baba"),
            new Cetrta.Prostor(5, 28, "bb"),
            new Cetrta.Prostor(9, 14, "bb"),
            new Cetrta.Prostor(6, 4, "baba"),
            new Cetrta.Prostor(9, 79, "bb"),
            new Cetrta.Prostor(3, 45, "aa"),
            new Cetrta.Prostor(8, 7, "aa"),
            new Cetrta.Prostor(1, 100, "bb"),
            new Cetrta.Prostor(6, 89, "aa"),
            new Cetrta.Prostor(2, 18, "aa"),
            new Cetrta.Prostor(6, 5, "abbbb"),
            new Cetrta.Prostor(10, 97, "baaba"),
            new Cetrta.Prostor(2, 59, "aa"),
            new Cetrta.Prostor(5, 15, "abbbb"),
            new Cetrta.Prostor(9, 66, "baaba"),
            new Cetrta.Prostor(8, 99, "baaba"),
            new Cetrta.Prostor(3, 78, "baba"),
            new Cetrta.Prostor(7, 46, "abbbb"),
            new Cetrta.Prostor(9, 22, "bb"),
            new Cetrta.Prostor(1, 3, "bb"),
            new Cetrta.Prostor(3, 75, "abbbb"),
            new Cetrta.Prostor(9, 75, "baba"),
            new Cetrta.Prostor(9, 3, "abbbb"),
            new Cetrta.Prostor(3, 37, "baaba"),
            new Cetrta.Prostor(6, 34, "bb"),
            new Cetrta.Prostor(3, 38, "baaba"),
            new Cetrta.Prostor(10, 10, "abbbb"),
            new Cetrta.Prostor(9, 40, "baaba"),
            new Cetrta.Prostor(4, 33, "baaba"),
            new Cetrta.Prostor(2, 74, "baaba"),
            new Cetrta.Prostor(9, 59, "abbbb"),
            new Cetrta.Prostor(6, 70, "baaba"),
            new Cetrta.Prostor(6, 27, "baaba"),
            new Cetrta.Prostor(1, 66, "baba"),
            new Cetrta.Prostor(7, 42, "baaba"),
            new Cetrta.Prostor(5, 82, "abbbb"),
            new Cetrta.Prostor(2, 49, "bb"),
            new Cetrta.Prostor(3, 97, "baaba"),
            new Cetrta.Prostor(3, 36, "baba"),
            new Cetrta.Prostor(6, 10, "aa"),
            new Cetrta.Prostor(7, 9, "aa"),
            new Cetrta.Prostor(9, 23, "aa"),
            new Cetrta.Prostor(6, 28, "baaba"),
            new Cetrta.Prostor(5, 33, "aa"),
            new Cetrta.Prostor(3, 80, "baba"),
            new Cetrta.Prostor(5, 68, "abbbb"),
            new Cetrta.Prostor(10, 61, "aa"),
            new Cetrta.Prostor(10, 57, "baba"),
            new Cetrta.Prostor(4, 78, "baba"),
            new Cetrta.Prostor(3, 15, "abbbb"),
            new Cetrta.Prostor(9, 72, "baaba"),
            new Cetrta.Prostor(2, 53, "bb"),
            new Cetrta.Prostor(5, 84, "aa"),
            new Cetrta.Prostor(5, 58, "bb"),
            new Cetrta.Prostor(5, 34, "abbbb"),
            new Cetrta.Prostor(6, 13, "baaba"),
            new Cetrta.Prostor(7, 34, "bb"),
            new Cetrta.Prostor(2, 48, "abbbb"),
            new Cetrta.Prostor(2, 20, "baba"),
            new Cetrta.Prostor(10, 22, "baaba"),
            new Cetrta.Prostor(2, 57, "baaba"),
            new Cetrta.Prostor(1, 18, "baaba"),
            new Cetrta.Prostor(10, 28, "aa"),
            new Cetrta.Prostor(8, 98, "baaba"),
            new Cetrta.Prostor(5, 17, "baaba"),
            new Cetrta.Prostor(8, 41, "baba"),
            new Cetrta.Prostor(1, 49, "bb"),
            new Cetrta.Prostor(2, 41, "bb"),
            new Cetrta.Prostor(8, 10, "baaba"),
            new Cetrta.Prostor(3, 17, "aa"),
            new Cetrta.Prostor(4, 40, "baaba"),
            new Cetrta.Prostor(5, 9, "abbbb"),
            new Cetrta.Prostor(9, 1, "bb"),
            new Cetrta.Prostor(4, 79, "baaba"),
            new Cetrta.Prostor(3, 54, "aa"),
            new Cetrta.Prostor(9, 53, "baba")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
