
import java.util.*;

public class Test18 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(3, 14, "aa"),
            new Cetrta.Prostor(4, 81, "bba"),
            new Cetrta.Prostor(1, 63, "ba"),
            new Cetrta.Prostor(2, 42, "ba"),
            new Cetrta.Prostor(2, 12, "ba"),
            new Cetrta.Prostor(2, 69, "bba"),
            new Cetrta.Prostor(3, 34, "bbab"),
            new Cetrta.Prostor(1, 42, "baaa"),
            new Cetrta.Prostor(4, 78, "bba"),
            new Cetrta.Prostor(2, 61, "ba"),
            new Cetrta.Prostor(3, 90, "bbab"),
            new Cetrta.Prostor(3, 23, "aa"),
            new Cetrta.Prostor(1, 47, "bbab"),
            new Cetrta.Prostor(1, 38, "bbab"),
            new Cetrta.Prostor(4, 23, "bba"),
            new Cetrta.Prostor(4, 31, "baaa"),
            new Cetrta.Prostor(4, 71, "bba"),
            new Cetrta.Prostor(1, 72, "ba"),
            new Cetrta.Prostor(3, 49, "bbaaa"),
            new Cetrta.Prostor(4, 54, "bbab"),
            new Cetrta.Prostor(2, 13, "ba"),
            new Cetrta.Prostor(3, 30, "aa"),
            new Cetrta.Prostor(4, 45, "bba"),
            new Cetrta.Prostor(2, 37, "ba"),
            new Cetrta.Prostor(4, 91, "aa"),
            new Cetrta.Prostor(3, 79, "bbab"),
            new Cetrta.Prostor(3, 72, "bbab"),
            new Cetrta.Prostor(2, 75, "aa"),
            new Cetrta.Prostor(3, 43, "aa"),
            new Cetrta.Prostor(4, 72, "bbab"),
            new Cetrta.Prostor(4, 46, "bbaaa"),
            new Cetrta.Prostor(3, 12, "bba"),
            new Cetrta.Prostor(1, 9, "bba"),
            new Cetrta.Prostor(2, 98, "bba"),
            new Cetrta.Prostor(1, 31, "bbaaa"),
            new Cetrta.Prostor(3, 27, "bba"),
            new Cetrta.Prostor(4, 7, "bbaaa"),
            new Cetrta.Prostor(2, 2, "ba"),
            new Cetrta.Prostor(4, 100, "bbab"),
            new Cetrta.Prostor(3, 26, "ba"),
            new Cetrta.Prostor(2, 3, "bbaaa"),
            new Cetrta.Prostor(2, 50, "ba"),
            new Cetrta.Prostor(3, 28, "aa"),
            new Cetrta.Prostor(3, 51, "bbab"),
            new Cetrta.Prostor(4, 58, "bbaaa"),
            new Cetrta.Prostor(4, 19, "aa"),
            new Cetrta.Prostor(2, 6, "bbaaa"),
            new Cetrta.Prostor(3, 62, "ba"),
            new Cetrta.Prostor(3, 18, "bba"),
            new Cetrta.Prostor(1, 71, "bbab"),
            new Cetrta.Prostor(1, 6, "bba"),
            new Cetrta.Prostor(2, 70, "bbaaa"),
            new Cetrta.Prostor(2, 60, "bbab"),
            new Cetrta.Prostor(3, 37, "bba"),
            new Cetrta.Prostor(2, 29, "ba"),
            new Cetrta.Prostor(3, 50, "aa"),
            new Cetrta.Prostor(1, 73, "ba"),
            new Cetrta.Prostor(3, 31, "baaa"),
            new Cetrta.Prostor(3, 54, "bbaaa"),
            new Cetrta.Prostor(2, 27, "aa"),
            new Cetrta.Prostor(4, 56, "baaa"),
            new Cetrta.Prostor(4, 17, "baaa"),
            new Cetrta.Prostor(1, 78, "baaa"),
            new Cetrta.Prostor(4, 87, "baaa"),
            new Cetrta.Prostor(1, 41, "bbaaa"),
            new Cetrta.Prostor(1, 26, "bbaaa"),
            new Cetrta.Prostor(3, 59, "ba"),
            new Cetrta.Prostor(2, 96, "ba"),
            new Cetrta.Prostor(3, 85, "bba"),
            new Cetrta.Prostor(2, 74, "bbaaa"),
            new Cetrta.Prostor(1, 46, "bbaaa"),
            new Cetrta.Prostor(3, 67, "bba"),
            new Cetrta.Prostor(2, 95, "ba"),
            new Cetrta.Prostor(1, 43, "baaa"),
            new Cetrta.Prostor(4, 20, "baaa"),
            new Cetrta.Prostor(4, 34, "baaa"),
            new Cetrta.Prostor(4, 70, "baaa"),
            new Cetrta.Prostor(1, 57, "baaa"),
            new Cetrta.Prostor(1, 74, "bbab"),
            new Cetrta.Prostor(2, 57, "aa"),
            new Cetrta.Prostor(1, 87, "baaa"),
            new Cetrta.Prostor(2, 24, "ba"),
            new Cetrta.Prostor(3, 89, "bbaaa"),
            new Cetrta.Prostor(1, 70, "aa"),
            new Cetrta.Prostor(1, 99, "bba"),
            new Cetrta.Prostor(1, 20, "aa")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
