
import java.util.*;

public class Test10 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 96, "baa"),
            new Cetrta.Prostor(3, 10, "bab"),
            new Cetrta.Prostor(3, 53, "baa"),
            new Cetrta.Prostor(3, 60, "ab"),
            new Cetrta.Prostor(4, 88, "bab"),
            new Cetrta.Prostor(3, 92, "ab"),
            new Cetrta.Prostor(1, 2, "baa"),
            new Cetrta.Prostor(1, 51, "ab"),
            new Cetrta.Prostor(1, 31, "baa"),
            new Cetrta.Prostor(4, 25, "ab"),
            new Cetrta.Prostor(3, 87, "bab"),
            new Cetrta.Prostor(1, 32, "bab"),
            new Cetrta.Prostor(1, 37, "baa"),
            new Cetrta.Prostor(1, 79, "ab"),
            new Cetrta.Prostor(4, 83, "ab"),
            new Cetrta.Prostor(1, 56, "ab"),
            new Cetrta.Prostor(3, 15, "baa"),
            new Cetrta.Prostor(2, 99, "ab"),
            new Cetrta.Prostor(1, 95, "ab"),
            new Cetrta.Prostor(1, 63, "baa"),
            new Cetrta.Prostor(2, 3, "baa"),
            new Cetrta.Prostor(1, 2, "baa"),
            new Cetrta.Prostor(3, 19, "bab"),
            new Cetrta.Prostor(1, 8, "baa"),
            new Cetrta.Prostor(4, 63, "bab"),
            new Cetrta.Prostor(4, 50, "baa"),
            new Cetrta.Prostor(4, 15, "bab"),
            new Cetrta.Prostor(2, 63, "baa"),
            new Cetrta.Prostor(4, 95, "baa"),
            new Cetrta.Prostor(1, 80, "baa"),
            new Cetrta.Prostor(1, 94, "ab"),
            new Cetrta.Prostor(4, 15, "bab"),
            new Cetrta.Prostor(2, 41, "ab"),
            new Cetrta.Prostor(3, 7, "ab"),
            new Cetrta.Prostor(2, 14, "bab"),
            new Cetrta.Prostor(1, 65, "ab"),
            new Cetrta.Prostor(4, 7, "bab"),
            new Cetrta.Prostor(2, 22, "ab"),
            new Cetrta.Prostor(3, 26, "bab"),
            new Cetrta.Prostor(1, 96, "ab"),
            new Cetrta.Prostor(4, 15, "ab"),
            new Cetrta.Prostor(3, 55, "baa"),
            new Cetrta.Prostor(4, 77, "ab"),
            new Cetrta.Prostor(3, 47, "baa"),
            new Cetrta.Prostor(4, 37, "bab"),
            new Cetrta.Prostor(1, 62, "bab"),
            new Cetrta.Prostor(3, 45, "baa"),
            new Cetrta.Prostor(4, 34, "bab"),
            new Cetrta.Prostor(4, 5, "bab"),
            new Cetrta.Prostor(2, 47, "baa"),
            new Cetrta.Prostor(3, 45, "bab"),
            new Cetrta.Prostor(1, 41, "ab"),
            new Cetrta.Prostor(4, 30, "bab"),
            new Cetrta.Prostor(3, 13, "ab"),
            new Cetrta.Prostor(1, 16, "baa"),
            new Cetrta.Prostor(3, 43, "ab"),
            new Cetrta.Prostor(3, 71, "ab"),
            new Cetrta.Prostor(1, 40, "bab"),
            new Cetrta.Prostor(4, 68, "bab"),
            new Cetrta.Prostor(2, 73, "baa"),
            new Cetrta.Prostor(4, 21, "bab"),
            new Cetrta.Prostor(4, 32, "baa"),
            new Cetrta.Prostor(2, 29, "bab"),
            new Cetrta.Prostor(4, 40, "baa"),
            new Cetrta.Prostor(1, 86, "ab"),
            new Cetrta.Prostor(4, 84, "baa"),
            new Cetrta.Prostor(4, 17, "baa"),
            new Cetrta.Prostor(2, 53, "baa"),
            new Cetrta.Prostor(4, 11, "baa"),
            new Cetrta.Prostor(1, 10, "bab"),
            new Cetrta.Prostor(2, 70, "baa"),
            new Cetrta.Prostor(3, 73, "bab"),
            new Cetrta.Prostor(1, 34, "baa"),
            new Cetrta.Prostor(3, 89, "bab"),
            new Cetrta.Prostor(3, 78, "bab"),
            new Cetrta.Prostor(1, 82, "bab"),
            new Cetrta.Prostor(1, 22, "bab"),
            new Cetrta.Prostor(4, 26, "baa"),
            new Cetrta.Prostor(1, 69, "bab"),
            new Cetrta.Prostor(1, 30, "bab"),
            new Cetrta.Prostor(2, 84, "bab"),
            new Cetrta.Prostor(2, 26, "baa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
