
import java.util.*;

public class Test20 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 5, "aab"),
            new Cetrta.Prostor(1, 48, "bb"),
            new Cetrta.Prostor(1, 49, "aab"),
            new Cetrta.Prostor(1, 10, "bab"),
            new Cetrta.Prostor(1, 59, "bb"),
            new Cetrta.Prostor(1, 87, "aaa"),
            new Cetrta.Prostor(1, 75, "bb"),
            new Cetrta.Prostor(1, 78, "bb"),
            new Cetrta.Prostor(1, 17, "abb"),
            new Cetrta.Prostor(1, 7, "aaa"),
            new Cetrta.Prostor(1, 80, "aab"),
            new Cetrta.Prostor(1, 16, "bab"),
            new Cetrta.Prostor(1, 23, "aaa"),
            new Cetrta.Prostor(1, 43, "bb"),
            new Cetrta.Prostor(1, 22, "aab"),
            new Cetrta.Prostor(1, 61, "bb"),
            new Cetrta.Prostor(1, 74, "bab"),
            new Cetrta.Prostor(1, 84, "aab"),
            new Cetrta.Prostor(1, 67, "aab"),
            new Cetrta.Prostor(1, 70, "bab"),
            new Cetrta.Prostor(1, 42, "bb"),
            new Cetrta.Prostor(1, 47, "bb"),
            new Cetrta.Prostor(1, 81, "bb"),
            new Cetrta.Prostor(1, 83, "bab"),
            new Cetrta.Prostor(1, 68, "abb"),
            new Cetrta.Prostor(1, 11, "aaa"),
            new Cetrta.Prostor(1, 3, "aab"),
            new Cetrta.Prostor(1, 60, "bb"),
            new Cetrta.Prostor(1, 90, "bab"),
            new Cetrta.Prostor(1, 97, "bb"),
            new Cetrta.Prostor(1, 13, "bb"),
            new Cetrta.Prostor(1, 29, "aab"),
            new Cetrta.Prostor(1, 88, "bb"),
            new Cetrta.Prostor(1, 26, "aab"),
            new Cetrta.Prostor(1, 25, "abb"),
            new Cetrta.Prostor(1, 55, "bab"),
            new Cetrta.Prostor(1, 24, "aaa"),
            new Cetrta.Prostor(1, 32, "bb"),
            new Cetrta.Prostor(1, 92, "bab"),
            new Cetrta.Prostor(1, 35, "aab"),
            new Cetrta.Prostor(1, 64, "bb"),
            new Cetrta.Prostor(1, 38, "aaa"),
            new Cetrta.Prostor(1, 44, "abb"),
            new Cetrta.Prostor(1, 91, "bb"),
            new Cetrta.Prostor(1, 33, "abb"),
            new Cetrta.Prostor(1, 40, "bb"),
            new Cetrta.Prostor(1, 19, "bb"),
            new Cetrta.Prostor(1, 76, "aaa"),
            new Cetrta.Prostor(1, 79, "bb"),
            new Cetrta.Prostor(1, 34, "aaa"),
            new Cetrta.Prostor(1, 71, "abb"),
            new Cetrta.Prostor(1, 93, "bb"),
            new Cetrta.Prostor(1, 9, "aab"),
            new Cetrta.Prostor(1, 82, "bb"),
            new Cetrta.Prostor(1, 66, "bab"),
            new Cetrta.Prostor(1, 12, "bb"),
            new Cetrta.Prostor(1, 58, "abb"),
            new Cetrta.Prostor(1, 31, "bab"),
            new Cetrta.Prostor(1, 89, "bab"),
            new Cetrta.Prostor(1, 30, "bb"),
            new Cetrta.Prostor(1, 54, "abb"),
            new Cetrta.Prostor(1, 4, "aab"),
            new Cetrta.Prostor(1, 63, "abb"),
            new Cetrta.Prostor(1, 96, "bb"),
            new Cetrta.Prostor(1, 98, "aab"),
            new Cetrta.Prostor(1, 65, "bab"),
            new Cetrta.Prostor(1, 28, "aaa"),
            new Cetrta.Prostor(1, 39, "aab"),
            new Cetrta.Prostor(1, 6, "bb"),
            new Cetrta.Prostor(1, 14, "aaa"),
            new Cetrta.Prostor(1, 53, "abb"),
            new Cetrta.Prostor(1, 8, "bb"),
            new Cetrta.Prostor(1, 41, "bb"),
            new Cetrta.Prostor(1, 77, "bb"),
            new Cetrta.Prostor(1, 2, "aab"),
            new Cetrta.Prostor(1, 37, "aab"),
            new Cetrta.Prostor(1, 100, "bb"),
            new Cetrta.Prostor(1, 45, "bab"),
            new Cetrta.Prostor(1, 21, "bb"),
            new Cetrta.Prostor(1, 95, "bb"),
            new Cetrta.Prostor(1, 36, "aab"),
            new Cetrta.Prostor(1, 86, "bb"),
            new Cetrta.Prostor(1, 85, "aab"),
            new Cetrta.Prostor(1, 51, "bb"),
            new Cetrta.Prostor(1, 46, "bb"),
            new Cetrta.Prostor(1, 52, "aab"),
            new Cetrta.Prostor(1, 1, "aaa"),
            new Cetrta.Prostor(1, 20, "bb"),
            new Cetrta.Prostor(1, 56, "abb"),
            new Cetrta.Prostor(1, 94, "bab"),
            new Cetrta.Prostor(1, 57, "aab"),
            new Cetrta.Prostor(1, 18, "abb")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
