
import java.util.*;

public class Test16 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(2, 34, "bab"),
            new Cetrta.Prostor(2, 76, "aba"),
            new Cetrta.Prostor(4, 25, "ba"),
            new Cetrta.Prostor(2, 74, "ab"),
            new Cetrta.Prostor(2, 76, "bab"),
            new Cetrta.Prostor(1, 5, "bab"),
            new Cetrta.Prostor(2, 56, "bbab"),
            new Cetrta.Prostor(1, 40, "abbbb"),
            new Cetrta.Prostor(4, 33, "aba"),
            new Cetrta.Prostor(3, 49, "abbbb"),
            new Cetrta.Prostor(3, 24, "bbab"),
            new Cetrta.Prostor(4, 23, "abbbb"),
            new Cetrta.Prostor(1, 3, "bbaab"),
            new Cetrta.Prostor(4, 69, "bbaab"),
            new Cetrta.Prostor(1, 77, "ab"),
            new Cetrta.Prostor(1, 62, "bbab"),
            new Cetrta.Prostor(2, 66, "abbbb"),
            new Cetrta.Prostor(1, 38, "abbbb"),
            new Cetrta.Prostor(4, 17, "bbaab"),
            new Cetrta.Prostor(4, 22, "bbab"),
            new Cetrta.Prostor(1, 20, "ab"),
            new Cetrta.Prostor(3, 82, "ab"),
            new Cetrta.Prostor(4, 15, "ab"),
            new Cetrta.Prostor(4, 4, "ab"),
            new Cetrta.Prostor(3, 53, "aba"),
            new Cetrta.Prostor(4, 76, "bbaab"),
            new Cetrta.Prostor(1, 56, "bbaab"),
            new Cetrta.Prostor(4, 9, "ab"),
            new Cetrta.Prostor(2, 43, "bbaab"),
            new Cetrta.Prostor(3, 60, "ab"),
            new Cetrta.Prostor(1, 71, "bab"),
            new Cetrta.Prostor(4, 34, "bbab"),
            new Cetrta.Prostor(3, 73, "bab"),
            new Cetrta.Prostor(4, 98, "ba"),
            new Cetrta.Prostor(3, 29, "bbab"),
            new Cetrta.Prostor(4, 11, "aba"),
            new Cetrta.Prostor(2, 15, "abbbb"),
            new Cetrta.Prostor(3, 7, "bbab"),
            new Cetrta.Prostor(4, 88, "aba"),
            new Cetrta.Prostor(3, 12, "aba"),
            new Cetrta.Prostor(3, 92, "ab"),
            new Cetrta.Prostor(1, 30, "ab"),
            new Cetrta.Prostor(3, 30, "abbbb"),
            new Cetrta.Prostor(4, 8, "aba"),
            new Cetrta.Prostor(2, 66, "bbaab"),
            new Cetrta.Prostor(4, 76, "bbaab"),
            new Cetrta.Prostor(1, 78, "aba"),
            new Cetrta.Prostor(1, 39, "abbbb"),
            new Cetrta.Prostor(2, 46, "bbab"),
            new Cetrta.Prostor(1, 82, "bbaab"),
            new Cetrta.Prostor(4, 75, "ba"),
            new Cetrta.Prostor(2, 11, "bab"),
            new Cetrta.Prostor(2, 46, "aba"),
            new Cetrta.Prostor(1, 43, "bab"),
            new Cetrta.Prostor(3, 50, "aba"),
            new Cetrta.Prostor(4, 96, "aba"),
            new Cetrta.Prostor(1, 67, "ab"),
            new Cetrta.Prostor(1, 76, "ab"),
            new Cetrta.Prostor(2, 22, "aba"),
            new Cetrta.Prostor(3, 30, "bbab"),
            new Cetrta.Prostor(4, 77, "ab"),
            new Cetrta.Prostor(2, 5, "bab"),
            new Cetrta.Prostor(2, 9, "abbbb"),
            new Cetrta.Prostor(4, 96, "abbbb"),
            new Cetrta.Prostor(2, 8, "bbab"),
            new Cetrta.Prostor(4, 68, "ba"),
            new Cetrta.Prostor(2, 26, "aba"),
            new Cetrta.Prostor(3, 26, "ba"),
            new Cetrta.Prostor(4, 12, "aba"),
            new Cetrta.Prostor(4, 92, "aba"),
            new Cetrta.Prostor(3, 17, "bab"),
            new Cetrta.Prostor(2, 86, "aba"),
            new Cetrta.Prostor(1, 82, "ab"),
            new Cetrta.Prostor(4, 97, "abbbb"),
            new Cetrta.Prostor(1, 21, "bbab"),
            new Cetrta.Prostor(1, 65, "aba"),
            new Cetrta.Prostor(4, 37, "bab"),
            new Cetrta.Prostor(1, 36, "aba"),
            new Cetrta.Prostor(4, 51, "abbbb"),
            new Cetrta.Prostor(4, 30, "aba"),
            new Cetrta.Prostor(1, 27, "ba"),
            new Cetrta.Prostor(1, 59, "abbbb"),
            new Cetrta.Prostor(3, 27, "ab"),
            new Cetrta.Prostor(1, 42, "bbaab"),
            new Cetrta.Prostor(1, 15, "ba"),
            new Cetrta.Prostor(3, 88, "bbaab"),
            new Cetrta.Prostor(2, 84, "abbbb"),
            new Cetrta.Prostor(1, 91, "bab")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
