
import java.util.*;

public class Test27 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 66, "aab"),
            new Cetrta.Prostor(2, 83, "aab"),
            new Cetrta.Prostor(4, 14, "aab"),
            new Cetrta.Prostor(5, 92, "aab"),
            new Cetrta.Prostor(1, 62, "aab"),
            new Cetrta.Prostor(5, 67, "aab"),
            new Cetrta.Prostor(3, 92, "aab"),
            new Cetrta.Prostor(1, 77, "aab"),
            new Cetrta.Prostor(4, 4, "aab"),
            new Cetrta.Prostor(5, 100, "aab"),
            new Cetrta.Prostor(1, 90, "aab"),
            new Cetrta.Prostor(4, 33, "aab"),
            new Cetrta.Prostor(4, 87, "aab"),
            new Cetrta.Prostor(4, 68, "aab"),
            new Cetrta.Prostor(2, 60, "aab"),
            new Cetrta.Prostor(1, 82, "aab"),
            new Cetrta.Prostor(5, 79, "aab"),
            new Cetrta.Prostor(4, 39, "aab"),
            new Cetrta.Prostor(3, 25, "aab"),
            new Cetrta.Prostor(4, 99, "aab"),
            new Cetrta.Prostor(2, 48, "aab"),
            new Cetrta.Prostor(3, 63, "aab"),
            new Cetrta.Prostor(1, 78, "aab"),
            new Cetrta.Prostor(4, 89, "aab"),
            new Cetrta.Prostor(2, 2, "aab"),
            new Cetrta.Prostor(4, 19, "aab"),
            new Cetrta.Prostor(1, 27, "aab"),
            new Cetrta.Prostor(5, 33, "aab"),
            new Cetrta.Prostor(2, 73, "aab"),
            new Cetrta.Prostor(5, 99, "aab"),
            new Cetrta.Prostor(2, 15, "aab"),
            new Cetrta.Prostor(4, 26, "aab"),
            new Cetrta.Prostor(2, 6, "aab"),
            new Cetrta.Prostor(1, 49, "aab"),
            new Cetrta.Prostor(2, 86, "aab"),
            new Cetrta.Prostor(1, 67, "aab"),
            new Cetrta.Prostor(2, 50, "aab"),
            new Cetrta.Prostor(3, 94, "aab"),
            new Cetrta.Prostor(3, 73, "aab"),
            new Cetrta.Prostor(4, 57, "aab"),
            new Cetrta.Prostor(3, 96, "aab"),
            new Cetrta.Prostor(3, 22, "aab"),
            new Cetrta.Prostor(2, 72, "aab"),
            new Cetrta.Prostor(2, 91, "aab"),
            new Cetrta.Prostor(2, 49, "aab"),
            new Cetrta.Prostor(5, 59, "aab"),
            new Cetrta.Prostor(5, 77, "aab"),
            new Cetrta.Prostor(5, 18, "aab"),
            new Cetrta.Prostor(4, 28, "aab"),
            new Cetrta.Prostor(3, 74, "aab"),
            new Cetrta.Prostor(2, 70, "aab"),
            new Cetrta.Prostor(2, 68, "aab"),
            new Cetrta.Prostor(5, 25, "aab"),
            new Cetrta.Prostor(4, 22, "aab"),
            new Cetrta.Prostor(3, 5, "aab"),
            new Cetrta.Prostor(5, 3, "aab"),
            new Cetrta.Prostor(1, 19, "aab"),
            new Cetrta.Prostor(5, 82, "aab"),
            new Cetrta.Prostor(3, 82, "aab"),
            new Cetrta.Prostor(1, 1, "aab"),
            new Cetrta.Prostor(1, 89, "aab"),
            new Cetrta.Prostor(3, 28, "aab"),
            new Cetrta.Prostor(2, 11, "aab"),
            new Cetrta.Prostor(4, 13, "aab"),
            new Cetrta.Prostor(4, 58, "aab"),
            new Cetrta.Prostor(4, 7, "aab"),
            new Cetrta.Prostor(1, 85, "aab"),
            new Cetrta.Prostor(5, 72, "aab"),
            new Cetrta.Prostor(2, 19, "aab"),
            new Cetrta.Prostor(5, 85, "aab"),
            new Cetrta.Prostor(4, 46, "aab"),
            new Cetrta.Prostor(2, 100, "aab"),
            new Cetrta.Prostor(3, 43, "aab"),
            new Cetrta.Prostor(5, 38, "aab"),
            new Cetrta.Prostor(3, 85, "aab"),
            new Cetrta.Prostor(5, 15, "aab"),
            new Cetrta.Prostor(1, 96, "aab"),
            new Cetrta.Prostor(3, 9, "aab"),
            new Cetrta.Prostor(3, 31, "aab"),
            new Cetrta.Prostor(3, 42, "aab"),
            new Cetrta.Prostor(3, 27, "aab"),
            new Cetrta.Prostor(5, 28, "aab")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
