
import java.util.*;

public class Test05 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(5, 9, "baa"),
            new Cetrta.Prostor(1, 95, "baa"),
            new Cetrta.Prostor(1, 85, "bbbab"),
            new Cetrta.Prostor(3, 34, "bbaa"),
            new Cetrta.Prostor(2, 85, "bbabb"),
            new Cetrta.Prostor(1, 52, "bbaa"),
            new Cetrta.Prostor(4, 71, "baa"),
            new Cetrta.Prostor(3, 7, "bbaab"),
            new Cetrta.Prostor(3, 60, "bbaa"),
            new Cetrta.Prostor(3, 97, "aaa"),
            new Cetrta.Prostor(1, 13, "bbabb"),
            new Cetrta.Prostor(4, 44, "bbbb"),
            new Cetrta.Prostor(3, 19, "aaa"),
            new Cetrta.Prostor(4, 2, "bba"),
            new Cetrta.Prostor(3, 45, "aaa"),
            new Cetrta.Prostor(4, 95, "bbabb"),
            new Cetrta.Prostor(3, 12, "baa"),
            new Cetrta.Prostor(3, 52, "bba"),
            new Cetrta.Prostor(4, 89, "bbaab"),
            new Cetrta.Prostor(5, 93, "bbbab"),
            new Cetrta.Prostor(1, 23, "bbaab"),
            new Cetrta.Prostor(3, 26, "baa"),
            new Cetrta.Prostor(4, 58, "bbaa"),
            new Cetrta.Prostor(4, 67, "bba"),
            new Cetrta.Prostor(4, 57, "bbbb"),
            new Cetrta.Prostor(4, 12, "bbbb"),
            new Cetrta.Prostor(1, 4, "bbbb"),
            new Cetrta.Prostor(2, 8, "aaa"),
            new Cetrta.Prostor(2, 43, "baa"),
            new Cetrta.Prostor(2, 6, "bbbb"),
            new Cetrta.Prostor(3, 81, "baa"),
            new Cetrta.Prostor(4, 56, "baa"),
            new Cetrta.Prostor(3, 25, "bbaa"),
            new Cetrta.Prostor(4, 82, "aaa"),
            new Cetrta.Prostor(2, 7, "bbaab"),
            new Cetrta.Prostor(4, 34, "bba"),
            new Cetrta.Prostor(3, 89, "bbbab"),
            new Cetrta.Prostor(4, 9, "bbabb"),
            new Cetrta.Prostor(1, 28, "bbbab"),
            new Cetrta.Prostor(3, 47, "bbaab"),
            new Cetrta.Prostor(2, 19, "baa"),
            new Cetrta.Prostor(4, 68, "bbaab"),
            new Cetrta.Prostor(3, 59, "bbbab"),
            new Cetrta.Prostor(2, 2, "bbaab"),
            new Cetrta.Prostor(5, 22, "bbbab"),
            new Cetrta.Prostor(4, 27, "bba"),
            new Cetrta.Prostor(2, 100, "baa"),
            new Cetrta.Prostor(5, 35, "bba"),
            new Cetrta.Prostor(3, 77, "bbaab"),
            new Cetrta.Prostor(4, 97, "bbbb"),
            new Cetrta.Prostor(4, 71, "bbaab"),
            new Cetrta.Prostor(5, 10, "bba"),
            new Cetrta.Prostor(1, 26, "bbbb"),
            new Cetrta.Prostor(1, 100, "baa"),
            new Cetrta.Prostor(5, 10, "baa"),
            new Cetrta.Prostor(4, 67, "bbbb"),
            new Cetrta.Prostor(2, 12, "bbaab"),
            new Cetrta.Prostor(1, 78, "bbabb"),
            new Cetrta.Prostor(2, 27, "baa"),
            new Cetrta.Prostor(1, 39, "bbbb"),
            new Cetrta.Prostor(1, 47, "bbaa"),
            new Cetrta.Prostor(5, 1, "bbaab"),
            new Cetrta.Prostor(5, 21, "bba"),
            new Cetrta.Prostor(2, 90, "bbbb"),
            new Cetrta.Prostor(2, 27, "bbabb"),
            new Cetrta.Prostor(3, 81, "bbbab"),
            new Cetrta.Prostor(1, 29, "bbaa"),
            new Cetrta.Prostor(2, 92, "bbaab"),
            new Cetrta.Prostor(5, 9, "bbaa"),
            new Cetrta.Prostor(3, 28, "bbbb"),
            new Cetrta.Prostor(2, 64, "baa"),
            new Cetrta.Prostor(1, 26, "aaa"),
            new Cetrta.Prostor(4, 36, "bbbb"),
            new Cetrta.Prostor(1, 42, "aaa"),
            new Cetrta.Prostor(1, 88, "aaa"),
            new Cetrta.Prostor(1, 94, "bbaa"),
            new Cetrta.Prostor(1, 31, "bbbb"),
            new Cetrta.Prostor(1, 74, "bbaa"),
            new Cetrta.Prostor(5, 90, "bbaa"),
            new Cetrta.Prostor(3, 92, "bbaa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
