
import java.util.*;

public class Test32 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(2, 29, "bb"),
            new Cetrta.Prostor(1, 65, "baab"),
            new Cetrta.Prostor(3, 21, "bb"),
            new Cetrta.Prostor(3, 41, "baab"),
            new Cetrta.Prostor(4, 93, "bb"),
            new Cetrta.Prostor(4, 75, "baab"),
            new Cetrta.Prostor(1, 64, "bb"),
            new Cetrta.Prostor(1, 99, "baab"),
            new Cetrta.Prostor(1, 41, "bb"),
            new Cetrta.Prostor(2, 67, "baab"),
            new Cetrta.Prostor(1, 90, "bb"),
            new Cetrta.Prostor(4, 22, "baab"),
            new Cetrta.Prostor(4, 54, "baab"),
            new Cetrta.Prostor(2, 85, "baab"),
            new Cetrta.Prostor(4, 59, "baab"),
            new Cetrta.Prostor(1, 78, "bb"),
            new Cetrta.Prostor(1, 11, "bb"),
            new Cetrta.Prostor(3, 98, "baab"),
            new Cetrta.Prostor(2, 54, "baab"),
            new Cetrta.Prostor(3, 63, "baab"),
            new Cetrta.Prostor(1, 2, "baab"),
            new Cetrta.Prostor(4, 29, "bb"),
            new Cetrta.Prostor(4, 27, "bb"),
            new Cetrta.Prostor(3, 49, "baab"),
            new Cetrta.Prostor(1, 7, "bb"),
            new Cetrta.Prostor(2, 26, "baab"),
            new Cetrta.Prostor(1, 88, "baab"),
            new Cetrta.Prostor(3, 82, "bb"),
            new Cetrta.Prostor(2, 81, "baab"),
            new Cetrta.Prostor(2, 87, "bb"),
            new Cetrta.Prostor(4, 17, "bb"),
            new Cetrta.Prostor(3, 62, "baab"),
            new Cetrta.Prostor(3, 76, "baab"),
            new Cetrta.Prostor(4, 39, "baab"),
            new Cetrta.Prostor(1, 22, "baab"),
            new Cetrta.Prostor(1, 9, "baab"),
            new Cetrta.Prostor(3, 61, "bb"),
            new Cetrta.Prostor(2, 97, "bb"),
            new Cetrta.Prostor(1, 1, "bb"),
            new Cetrta.Prostor(2, 7, "baab"),
            new Cetrta.Prostor(2, 15, "baab"),
            new Cetrta.Prostor(4, 11, "baab"),
            new Cetrta.Prostor(4, 52, "bb"),
            new Cetrta.Prostor(1, 43, "baab"),
            new Cetrta.Prostor(2, 88, "baab"),
            new Cetrta.Prostor(2, 66, "baab"),
            new Cetrta.Prostor(1, 92, "baab"),
            new Cetrta.Prostor(2, 61, "bb"),
            new Cetrta.Prostor(2, 70, "baab"),
            new Cetrta.Prostor(4, 30, "baab"),
            new Cetrta.Prostor(2, 68, "baab"),
            new Cetrta.Prostor(4, 60, "baab"),
            new Cetrta.Prostor(2, 71, "baab"),
            new Cetrta.Prostor(2, 3, "baab"),
            new Cetrta.Prostor(1, 86, "bb"),
            new Cetrta.Prostor(4, 70, "baab"),
            new Cetrta.Prostor(4, 76, "baab"),
            new Cetrta.Prostor(4, 92, "baab"),
            new Cetrta.Prostor(4, 99, "bb"),
            new Cetrta.Prostor(4, 62, "baab"),
            new Cetrta.Prostor(1, 74, "bb"),
            new Cetrta.Prostor(2, 65, "bb"),
            new Cetrta.Prostor(2, 5, "baab"),
            new Cetrta.Prostor(1, 35, "baab"),
            new Cetrta.Prostor(3, 88, "bb"),
            new Cetrta.Prostor(4, 86, "bb"),
            new Cetrta.Prostor(3, 79, "baab"),
            new Cetrta.Prostor(2, 77, "bb"),
            new Cetrta.Prostor(3, 55, "baab"),
            new Cetrta.Prostor(4, 81, "baab"),
            new Cetrta.Prostor(3, 37, "baab"),
            new Cetrta.Prostor(1, 58, "baab"),
            new Cetrta.Prostor(4, 66, "bb"),
            new Cetrta.Prostor(2, 57, "bb"),
            new Cetrta.Prostor(3, 54, "baab"),
            new Cetrta.Prostor(1, 72, "bb"),
            new Cetrta.Prostor(3, 73, "bb"),
            new Cetrta.Prostor(3, 36, "bb"),
            new Cetrta.Prostor(2, 13, "bb"),
            new Cetrta.Prostor(2, 10, "baab"),
            new Cetrta.Prostor(1, 34, "bb"),
            new Cetrta.Prostor(2, 23, "bb"),
            new Cetrta.Prostor(3, 38, "bb"),
            new Cetrta.Prostor(4, 8, "bb"),
            new Cetrta.Prostor(3, 91, "bb"),
            new Cetrta.Prostor(2, 98, "baab"),
            new Cetrta.Prostor(3, 16, "baab"),
            new Cetrta.Prostor(3, 31, "baab"),
            new Cetrta.Prostor(3, 66, "bb"),
            new Cetrta.Prostor(2, 52, "bb"),
            new Cetrta.Prostor(1, 69, "bb"),
            new Cetrta.Prostor(4, 58, "baab"),
            new Cetrta.Prostor(1, 8, "baab"),
            new Cetrta.Prostor(4, 7, "baab"),
            new Cetrta.Prostor(3, 4, "baab")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
