
import java.util.*;

public class Test03 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 41, "ba"),
            new Cetrta.Prostor(1, 66, "bbb"),
            new Cetrta.Prostor(1, 60, "babb"),
            new Cetrta.Prostor(2, 63, "bbb"),
            new Cetrta.Prostor(1, 51, "ab"),
            new Cetrta.Prostor(2, 20, "bbb"),
            new Cetrta.Prostor(1, 11, "abbaa"),
            new Cetrta.Prostor(1, 74, "babb"),
            new Cetrta.Prostor(2, 46, "ba"),
            new Cetrta.Prostor(2, 83, "baaba"),
            new Cetrta.Prostor(2, 57, "babb"),
            new Cetrta.Prostor(2, 2, "ab"),
            new Cetrta.Prostor(1, 61, "ba"),
            new Cetrta.Prostor(1, 63, "ba"),
            new Cetrta.Prostor(2, 79, "baaba"),
            new Cetrta.Prostor(1, 67, "ba"),
            new Cetrta.Prostor(1, 79, "ba"),
            new Cetrta.Prostor(1, 85, "bbb"),
            new Cetrta.Prostor(1, 34, "ab"),
            new Cetrta.Prostor(2, 48, "baaba"),
            new Cetrta.Prostor(2, 91, "baaba"),
            new Cetrta.Prostor(2, 85, "ba"),
            new Cetrta.Prostor(1, 38, "babb"),
            new Cetrta.Prostor(1, 100, "baaba"),
            new Cetrta.Prostor(1, 51, "ba"),
            new Cetrta.Prostor(1, 20, "ba"),
            new Cetrta.Prostor(1, 51, "baaba"),
            new Cetrta.Prostor(2, 6, "babb"),
            new Cetrta.Prostor(2, 75, "ab"),
            new Cetrta.Prostor(2, 96, "abbaa"),
            new Cetrta.Prostor(1, 67, "babb"),
            new Cetrta.Prostor(2, 67, "ba"),
            new Cetrta.Prostor(1, 81, "babb"),
            new Cetrta.Prostor(2, 16, "babb"),
            new Cetrta.Prostor(1, 3, "ab"),
            new Cetrta.Prostor(2, 53, "ba"),
            new Cetrta.Prostor(2, 83, "baaba"),
            new Cetrta.Prostor(1, 17, "baaba"),
            new Cetrta.Prostor(2, 64, "bbb"),
            new Cetrta.Prostor(1, 15, "bbb"),
            new Cetrta.Prostor(1, 77, "ba"),
            new Cetrta.Prostor(1, 51, "abbaa"),
            new Cetrta.Prostor(1, 87, "ba"),
            new Cetrta.Prostor(2, 28, "abbaa"),
            new Cetrta.Prostor(2, 19, "ba"),
            new Cetrta.Prostor(2, 24, "ab"),
            new Cetrta.Prostor(1, 88, "ab"),
            new Cetrta.Prostor(1, 27, "baaba"),
            new Cetrta.Prostor(2, 21, "ab"),
            new Cetrta.Prostor(1, 42, "bbb"),
            new Cetrta.Prostor(2, 14, "abbaa"),
            new Cetrta.Prostor(1, 87, "abbaa"),
            new Cetrta.Prostor(1, 13, "bbb"),
            new Cetrta.Prostor(1, 5, "bbb"),
            new Cetrta.Prostor(1, 65, "abbaa"),
            new Cetrta.Prostor(2, 19, "ab"),
            new Cetrta.Prostor(2, 89, "ba"),
            new Cetrta.Prostor(1, 51, "babb"),
            new Cetrta.Prostor(1, 62, "ab"),
            new Cetrta.Prostor(2, 42, "ba"),
            new Cetrta.Prostor(2, 95, "abbaa"),
            new Cetrta.Prostor(2, 58, "abbaa"),
            new Cetrta.Prostor(1, 2, "abbaa"),
            new Cetrta.Prostor(1, 39, "ba"),
            new Cetrta.Prostor(1, 63, "ba"),
            new Cetrta.Prostor(2, 32, "abbaa"),
            new Cetrta.Prostor(1, 8, "baaba"),
            new Cetrta.Prostor(2, 55, "ba"),
            new Cetrta.Prostor(1, 84, "baaba"),
            new Cetrta.Prostor(2, 39, "abbaa"),
            new Cetrta.Prostor(1, 88, "ba"),
            new Cetrta.Prostor(2, 26, "ab"),
            new Cetrta.Prostor(1, 53, "ba"),
            new Cetrta.Prostor(2, 49, "ba"),
            new Cetrta.Prostor(2, 15, "ab"),
            new Cetrta.Prostor(2, 56, "ba"),
            new Cetrta.Prostor(1, 62, "abbaa"),
            new Cetrta.Prostor(1, 42, "bbb"),
            new Cetrta.Prostor(2, 79, "ba"),
            new Cetrta.Prostor(1, 75, "abbaa"),
            new Cetrta.Prostor(1, 4, "ba"),
            new Cetrta.Prostor(1, 91, "baaba"),
            new Cetrta.Prostor(2, 67, "baaba"),
            new Cetrta.Prostor(1, 67, "bbb"),
            new Cetrta.Prostor(2, 34, "babb"),
            new Cetrta.Prostor(2, 100, "bbb"),
            new Cetrta.Prostor(1, 52, "baaba"),
            new Cetrta.Prostor(2, 100, "babb"),
            new Cetrta.Prostor(1, 1, "babb"),
            new Cetrta.Prostor(1, 69, "babb"),
            new Cetrta.Prostor(2, 64, "ba"),
            new Cetrta.Prostor(2, 44, "abbaa"),
            new Cetrta.Prostor(2, 49, "bbb"),
            new Cetrta.Prostor(1, 73, "babb"),
            new Cetrta.Prostor(2, 86, "ab")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
