
import java.util.*;

public class Test06 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(7, 22, "aab"),
            new Cetrta.Prostor(6, 32, "aa"),
            new Cetrta.Prostor(1, 79, "aa"),
            new Cetrta.Prostor(5, 92, "aab"),
            new Cetrta.Prostor(5, 77, "aaaa"),
            new Cetrta.Prostor(7, 29, "aba"),
            new Cetrta.Prostor(6, 95, "aaaa"),
            new Cetrta.Prostor(1, 74, "aaaa"),
            new Cetrta.Prostor(2, 8, "aab"),
            new Cetrta.Prostor(2, 100, "aab"),
            new Cetrta.Prostor(1, 1, "aab"),
            new Cetrta.Prostor(5, 57, "bbb"),
            new Cetrta.Prostor(3, 67, "aa"),
            new Cetrta.Prostor(2, 16, "aa"),
            new Cetrta.Prostor(7, 72, "bbb"),
            new Cetrta.Prostor(4, 96, "aab"),
            new Cetrta.Prostor(5, 91, "aba"),
            new Cetrta.Prostor(7, 15, "aba"),
            new Cetrta.Prostor(3, 34, "aba"),
            new Cetrta.Prostor(1, 78, "bbb"),
            new Cetrta.Prostor(4, 50, "aab"),
            new Cetrta.Prostor(4, 85, "bbb"),
            new Cetrta.Prostor(5, 21, "aab"),
            new Cetrta.Prostor(2, 54, "aba"),
            new Cetrta.Prostor(2, 98, "aaaa"),
            new Cetrta.Prostor(2, 69, "bbb"),
            new Cetrta.Prostor(1, 52, "aaaa"),
            new Cetrta.Prostor(3, 36, "bbb"),
            new Cetrta.Prostor(2, 21, "aaaa"),
            new Cetrta.Prostor(3, 86, "aab"),
            new Cetrta.Prostor(6, 68, "aaaa"),
            new Cetrta.Prostor(1, 80, "aab"),
            new Cetrta.Prostor(2, 44, "aaaa"),
            new Cetrta.Prostor(4, 52, "bbb"),
            new Cetrta.Prostor(5, 54, "bbb"),
            new Cetrta.Prostor(7, 38, "aba"),
            new Cetrta.Prostor(5, 26, "aab"),
            new Cetrta.Prostor(1, 30, "aab"),
            new Cetrta.Prostor(6, 73, "aba"),
            new Cetrta.Prostor(2, 79, "aa"),
            new Cetrta.Prostor(2, 32, "aab"),
            new Cetrta.Prostor(1, 81, "aaaa"),
            new Cetrta.Prostor(5, 99, "aa"),
            new Cetrta.Prostor(3, 38, "bbb"),
            new Cetrta.Prostor(1, 55, "aab"),
            new Cetrta.Prostor(1, 50, "bbb"),
            new Cetrta.Prostor(6, 33, "aaaa"),
            new Cetrta.Prostor(2, 96, "aaaa"),
            new Cetrta.Prostor(6, 83, "aaaa"),
            new Cetrta.Prostor(4, 32, "aba"),
            new Cetrta.Prostor(4, 57, "aaaa"),
            new Cetrta.Prostor(4, 82, "aba"),
            new Cetrta.Prostor(2, 58, "aba"),
            new Cetrta.Prostor(6, 86, "bbb"),
            new Cetrta.Prostor(5, 7, "aba"),
            new Cetrta.Prostor(6, 13, "aab"),
            new Cetrta.Prostor(3, 10, "aaaa"),
            new Cetrta.Prostor(4, 86, "bbb"),
            new Cetrta.Prostor(3, 64, "aba"),
            new Cetrta.Prostor(3, 76, "aab"),
            new Cetrta.Prostor(1, 38, "aaaa"),
            new Cetrta.Prostor(1, 3, "bbb"),
            new Cetrta.Prostor(2, 7, "aa"),
            new Cetrta.Prostor(4, 63, "aa"),
            new Cetrta.Prostor(4, 32, "aaaa"),
            new Cetrta.Prostor(2, 23, "aba"),
            new Cetrta.Prostor(3, 42, "aba"),
            new Cetrta.Prostor(1, 7, "aaaa"),
            new Cetrta.Prostor(6, 52, "bbb"),
            new Cetrta.Prostor(6, 31, "bbb"),
            new Cetrta.Prostor(2, 32, "aab"),
            new Cetrta.Prostor(3, 89, "bbb"),
            new Cetrta.Prostor(7, 36, "aba"),
            new Cetrta.Prostor(6, 98, "aa"),
            new Cetrta.Prostor(6, 80, "bbb"),
            new Cetrta.Prostor(7, 7, "aba"),
            new Cetrta.Prostor(6, 23, "aa"),
            new Cetrta.Prostor(4, 36, "aab"),
            new Cetrta.Prostor(5, 79, "aaaa"),
            new Cetrta.Prostor(7, 51, "aaaa"),
            new Cetrta.Prostor(1, 48, "aab"),
            new Cetrta.Prostor(7, 40, "aa"),
            new Cetrta.Prostor(6, 53, "aba"),
            new Cetrta.Prostor(1, 53, "aab"),
            new Cetrta.Prostor(7, 90, "aa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
