
import java.util.*;

public class Test07 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(3, 29, "abbaa"),
            new Cetrta.Prostor(1, 60, "aaaa"),
            new Cetrta.Prostor(3, 37, "ab"),
            new Cetrta.Prostor(2, 57, "aaaa"),
            new Cetrta.Prostor(3, 49, "aaaa"),
            new Cetrta.Prostor(2, 78, "abb"),
            new Cetrta.Prostor(1, 52, "aaaa"),
            new Cetrta.Prostor(2, 55, "aaaa"),
            new Cetrta.Prostor(3, 70, "abb"),
            new Cetrta.Prostor(1, 66, "aaabb"),
            new Cetrta.Prostor(1, 5, "ab"),
            new Cetrta.Prostor(2, 58, "ab"),
            new Cetrta.Prostor(2, 26, "abbaa"),
            new Cetrta.Prostor(3, 36, "aaab"),
            new Cetrta.Prostor(1, 7, "abbb"),
            new Cetrta.Prostor(2, 56, "abb"),
            new Cetrta.Prostor(2, 45, "ab"),
            new Cetrta.Prostor(3, 58, "aaab"),
            new Cetrta.Prostor(3, 46, "abbaa"),
            new Cetrta.Prostor(3, 7, "abb"),
            new Cetrta.Prostor(1, 23, "abbb"),
            new Cetrta.Prostor(1, 6, "abb"),
            new Cetrta.Prostor(2, 17, "aaabb"),
            new Cetrta.Prostor(2, 30, "abbaa"),
            new Cetrta.Prostor(1, 87, "aaaa"),
            new Cetrta.Prostor(3, 19, "aaabb"),
            new Cetrta.Prostor(3, 4, "aaaa"),
            new Cetrta.Prostor(2, 98, "aaab"),
            new Cetrta.Prostor(2, 44, "aaab"),
            new Cetrta.Prostor(2, 22, "ab"),
            new Cetrta.Prostor(1, 4, "ab"),
            new Cetrta.Prostor(2, 51, "aaab"),
            new Cetrta.Prostor(2, 100, "ab"),
            new Cetrta.Prostor(2, 19, "aaab"),
            new Cetrta.Prostor(1, 17, "aaabb"),
            new Cetrta.Prostor(1, 5, "aaabb"),
            new Cetrta.Prostor(2, 4, "ab"),
            new Cetrta.Prostor(1, 23, "abbaa"),
            new Cetrta.Prostor(2, 39, "abbb"),
            new Cetrta.Prostor(1, 10, "aaaa"),
            new Cetrta.Prostor(3, 50, "abbb"),
            new Cetrta.Prostor(2, 29, "aaabb"),
            new Cetrta.Prostor(2, 47, "aaabb"),
            new Cetrta.Prostor(2, 88, "aaab"),
            new Cetrta.Prostor(3, 27, "aaaa"),
            new Cetrta.Prostor(3, 98, "aaab"),
            new Cetrta.Prostor(2, 51, "abbaa"),
            new Cetrta.Prostor(2, 5, "aaabb"),
            new Cetrta.Prostor(2, 13, "aaabb"),
            new Cetrta.Prostor(3, 5, "abbb"),
            new Cetrta.Prostor(3, 22, "aaaa"),
            new Cetrta.Prostor(1, 43, "abb"),
            new Cetrta.Prostor(3, 72, "abbaa"),
            new Cetrta.Prostor(3, 39, "aaabb"),
            new Cetrta.Prostor(2, 18, "ab"),
            new Cetrta.Prostor(1, 42, "abbaa"),
            new Cetrta.Prostor(3, 21, "abbaa"),
            new Cetrta.Prostor(2, 11, "aaabb"),
            new Cetrta.Prostor(1, 59, "aaabb"),
            new Cetrta.Prostor(2, 41, "aaabb"),
            new Cetrta.Prostor(3, 91, "aaabb"),
            new Cetrta.Prostor(2, 24, "aaaa"),
            new Cetrta.Prostor(3, 61, "aaab"),
            new Cetrta.Prostor(1, 12, "aaaa"),
            new Cetrta.Prostor(3, 54, "abbb"),
            new Cetrta.Prostor(2, 92, "ab"),
            new Cetrta.Prostor(1, 68, "ab"),
            new Cetrta.Prostor(3, 12, "aaabb"),
            new Cetrta.Prostor(3, 35, "abbaa"),
            new Cetrta.Prostor(2, 76, "abb"),
            new Cetrta.Prostor(2, 48, "aaabb"),
            new Cetrta.Prostor(3, 15, "ab"),
            new Cetrta.Prostor(1, 57, "abb"),
            new Cetrta.Prostor(1, 12, "abb"),
            new Cetrta.Prostor(2, 58, "aaaa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
