
import java.util.*;

public class Test17 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(2, 81, "bab"),
            new Cetrta.Prostor(3, 73, "aaba"),
            new Cetrta.Prostor(2, 71, "aaba"),
            new Cetrta.Prostor(1, 49, "bb"),
            new Cetrta.Prostor(3, 6, "bb"),
            new Cetrta.Prostor(1, 6, "abbb"),
            new Cetrta.Prostor(1, 72, "bb"),
            new Cetrta.Prostor(1, 25, "bbaa"),
            new Cetrta.Prostor(3, 84, "bb"),
            new Cetrta.Prostor(1, 38, "abbb"),
            new Cetrta.Prostor(1, 81, "bbaa"),
            new Cetrta.Prostor(3, 33, "bb"),
            new Cetrta.Prostor(1, 46, "bab"),
            new Cetrta.Prostor(1, 61, "aaba"),
            new Cetrta.Prostor(3, 70, "bb"),
            new Cetrta.Prostor(3, 59, "abbb"),
            new Cetrta.Prostor(3, 73, "bab"),
            new Cetrta.Prostor(1, 28, "abbb"),
            new Cetrta.Prostor(2, 84, "abbb"),
            new Cetrta.Prostor(3, 15, "aaba"),
            new Cetrta.Prostor(1, 66, "bb"),
            new Cetrta.Prostor(1, 4, "bb"),
            new Cetrta.Prostor(2, 23, "bab"),
            new Cetrta.Prostor(1, 39, "bbaa"),
            new Cetrta.Prostor(2, 40, "bab"),
            new Cetrta.Prostor(2, 21, "aaba"),
            new Cetrta.Prostor(2, 75, "bb"),
            new Cetrta.Prostor(2, 35, "abbb"),
            new Cetrta.Prostor(3, 4, "bb"),
            new Cetrta.Prostor(2, 34, "bab"),
            new Cetrta.Prostor(1, 77, "abbb"),
            new Cetrta.Prostor(1, 67, "bb"),
            new Cetrta.Prostor(2, 40, "bbaa"),
            new Cetrta.Prostor(2, 81, "bb"),
            new Cetrta.Prostor(3, 45, "bb"),
            new Cetrta.Prostor(3, 87, "bb"),
            new Cetrta.Prostor(3, 30, "abbb"),
            new Cetrta.Prostor(1, 35, "bbaa"),
            new Cetrta.Prostor(3, 37, "aaba"),
            new Cetrta.Prostor(1, 74, "bb"),
            new Cetrta.Prostor(2, 98, "abbb"),
            new Cetrta.Prostor(2, 80, "bab"),
            new Cetrta.Prostor(1, 67, "bbaa"),
            new Cetrta.Prostor(2, 53, "abbb"),
            new Cetrta.Prostor(2, 25, "abbb"),
            new Cetrta.Prostor(2, 47, "bbaa"),
            new Cetrta.Prostor(3, 76, "bb"),
            new Cetrta.Prostor(1, 8, "abbb"),
            new Cetrta.Prostor(2, 42, "bb"),
            new Cetrta.Prostor(3, 15, "aaba"),
            new Cetrta.Prostor(3, 93, "abbb"),
            new Cetrta.Prostor(2, 71, "abbb"),
            new Cetrta.Prostor(2, 55, "abbb"),
            new Cetrta.Prostor(3, 46, "bbaa"),
            new Cetrta.Prostor(1, 39, "bab"),
            new Cetrta.Prostor(3, 64, "abbb"),
            new Cetrta.Prostor(2, 9, "bb"),
            new Cetrta.Prostor(1, 68, "abbb"),
            new Cetrta.Prostor(1, 61, "bbaa"),
            new Cetrta.Prostor(3, 46, "aaba"),
            new Cetrta.Prostor(1, 90, "abbb"),
            new Cetrta.Prostor(2, 67, "bb"),
            new Cetrta.Prostor(3, 53, "bb"),
            new Cetrta.Prostor(3, 83, "abbb"),
            new Cetrta.Prostor(2, 70, "bab"),
            new Cetrta.Prostor(2, 9, "bbaa"),
            new Cetrta.Prostor(3, 83, "aaba"),
            new Cetrta.Prostor(2, 1, "bb"),
            new Cetrta.Prostor(3, 72, "bbaa"),
            new Cetrta.Prostor(2, 94, "bbaa"),
            new Cetrta.Prostor(3, 52, "abbb")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
