
import java.util.*;

public class Test31 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(6, 49, "aba"),
            new Cetrta.Prostor(6, 51, "bbaaa"),
            new Cetrta.Prostor(4, 94, "aba"),
            new Cetrta.Prostor(2, 7, "ba"),
            new Cetrta.Prostor(1, 45, "ba"),
            new Cetrta.Prostor(2, 2, "bbaaa"),
            new Cetrta.Prostor(3, 16, "aba"),
            new Cetrta.Prostor(5, 53, "ba"),
            new Cetrta.Prostor(4, 46, "aba"),
            new Cetrta.Prostor(2, 62, "aaab"),
            new Cetrta.Prostor(4, 52, "aaabb"),
            new Cetrta.Prostor(2, 20, "bbaaa"),
            new Cetrta.Prostor(2, 10, "aaabb"),
            new Cetrta.Prostor(4, 48, "ba"),
            new Cetrta.Prostor(1, 69, "aba"),
            new Cetrta.Prostor(1, 8, "aaabb"),
            new Cetrta.Prostor(6, 44, "aaab"),
            new Cetrta.Prostor(5, 30, "aaab"),
            new Cetrta.Prostor(5, 21, "aaab"),
            new Cetrta.Prostor(6, 53, "aaab"),
            new Cetrta.Prostor(1, 56, "aba"),
            new Cetrta.Prostor(2, 83, "aaabb"),
            new Cetrta.Prostor(3, 10, "ba"),
            new Cetrta.Prostor(2, 76, "bbaaa"),
            new Cetrta.Prostor(3, 13, "aba"),
            new Cetrta.Prostor(1, 97, "ba"),
            new Cetrta.Prostor(3, 94, "aba"),
            new Cetrta.Prostor(2, 80, "ba"),
            new Cetrta.Prostor(6, 73, "bbaaa"),
            new Cetrta.Prostor(6, 50, "aaabb"),
            new Cetrta.Prostor(4, 88, "aba"),
            new Cetrta.Prostor(6, 87, "bbaaa"),
            new Cetrta.Prostor(5, 9, "aba"),
            new Cetrta.Prostor(5, 93, "bbaaa"),
            new Cetrta.Prostor(4, 5, "aba"),
            new Cetrta.Prostor(2, 87, "ba"),
            new Cetrta.Prostor(4, 89, "aaabb"),
            new Cetrta.Prostor(2, 90, "aaabb"),
            new Cetrta.Prostor(5, 92, "bbaaa"),
            new Cetrta.Prostor(2, 18, "aaab"),
            new Cetrta.Prostor(6, 28, "aaab"),
            new Cetrta.Prostor(3, 12, "aaab"),
            new Cetrta.Prostor(3, 56, "aba"),
            new Cetrta.Prostor(1, 2, "bbaaa"),
            new Cetrta.Prostor(3, 8, "aba"),
            new Cetrta.Prostor(3, 2, "aaab"),
            new Cetrta.Prostor(2, 45, "aaabb"),
            new Cetrta.Prostor(5, 80, "aba"),
            new Cetrta.Prostor(6, 14, "aaab"),
            new Cetrta.Prostor(1, 70, "aaab"),
            new Cetrta.Prostor(6, 46, "aaabb"),
            new Cetrta.Prostor(4, 79, "aaabb"),
            new Cetrta.Prostor(6, 70, "aba"),
            new Cetrta.Prostor(2, 3, "ba"),
            new Cetrta.Prostor(1, 76, "aaabb"),
            new Cetrta.Prostor(1, 5, "aaab"),
            new Cetrta.Prostor(4, 24, "bbaaa"),
            new Cetrta.Prostor(4, 14, "aaab"),
            new Cetrta.Prostor(2, 92, "aba"),
            new Cetrta.Prostor(2, 41, "bbaaa"),
            new Cetrta.Prostor(3, 66, "aaabb"),
            new Cetrta.Prostor(5, 27, "aaab"),
            new Cetrta.Prostor(1, 58, "aaabb"),
            new Cetrta.Prostor(2, 97, "aaab"),
            new Cetrta.Prostor(4, 55, "aaab"),
            new Cetrta.Prostor(2, 32, "ba"),
            new Cetrta.Prostor(4, 3, "aba"),
            new Cetrta.Prostor(3, 99, "aaab"),
            new Cetrta.Prostor(4, 98, "aba"),
            new Cetrta.Prostor(4, 76, "aba"),
            new Cetrta.Prostor(4, 32, "aaabb"),
            new Cetrta.Prostor(3, 29, "ba"),
            new Cetrta.Prostor(3, 11, "aaab"),
            new Cetrta.Prostor(6, 85, "aba"),
            new Cetrta.Prostor(1, 50, "ba"),
            new Cetrta.Prostor(6, 31, "bbaaa"),
            new Cetrta.Prostor(5, 94, "bbaaa"),
            new Cetrta.Prostor(3, 27, "aaabb"),
            new Cetrta.Prostor(5, 19, "bbaaa"),
            new Cetrta.Prostor(3, 78, "aaabb"),
            new Cetrta.Prostor(2, 67, "aaab"),
            new Cetrta.Prostor(5, 62, "bbaaa"),
            new Cetrta.Prostor(5, 18, "aba"),
            new Cetrta.Prostor(2, 95, "bbaaa"),
            new Cetrta.Prostor(2, 30, "bbaaa"),
            new Cetrta.Prostor(4, 43, "ba")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
