
import java.util.*;

public class Test13 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 76, "aaaa"),
            new Cetrta.Prostor(5, 2, "ab"),
            new Cetrta.Prostor(4, 13, "aaaa"),
            new Cetrta.Prostor(1, 67, "aaaa"),
            new Cetrta.Prostor(2, 66, "abba"),
            new Cetrta.Prostor(5, 11, "bbab"),
            new Cetrta.Prostor(5, 55, "bbbab"),
            new Cetrta.Prostor(3, 80, "bbbab"),
            new Cetrta.Prostor(5, 44, "bbab"),
            new Cetrta.Prostor(2, 37, "aaaa"),
            new Cetrta.Prostor(5, 65, "ab"),
            new Cetrta.Prostor(4, 76, "bbab"),
            new Cetrta.Prostor(1, 49, "aaaa"),
            new Cetrta.Prostor(1, 18, "bbab"),
            new Cetrta.Prostor(3, 44, "aaaa"),
            new Cetrta.Prostor(5, 48, "ab"),
            new Cetrta.Prostor(2, 61, "bbbab"),
            new Cetrta.Prostor(2, 37, "abba"),
            new Cetrta.Prostor(2, 83, "abba"),
            new Cetrta.Prostor(3, 58, "bbab"),
            new Cetrta.Prostor(5, 5, "bbab"),
            new Cetrta.Prostor(2, 19, "ab"),
            new Cetrta.Prostor(2, 77, "aaaa"),
            new Cetrta.Prostor(4, 26, "bbbab"),
            new Cetrta.Prostor(1, 82, "aaaa"),
            new Cetrta.Prostor(2, 80, "bbbab"),
            new Cetrta.Prostor(1, 39, "aaaa"),
            new Cetrta.Prostor(3, 13, "abba"),
            new Cetrta.Prostor(4, 93, "ab"),
            new Cetrta.Prostor(2, 100, "bbab"),
            new Cetrta.Prostor(5, 73, "aaaa"),
            new Cetrta.Prostor(5, 45, "ab"),
            new Cetrta.Prostor(1, 1, "ab"),
            new Cetrta.Prostor(4, 72, "bbbab"),
            new Cetrta.Prostor(4, 27, "bbab"),
            new Cetrta.Prostor(5, 34, "abba"),
            new Cetrta.Prostor(2, 54, "abba"),
            new Cetrta.Prostor(4, 33, "aaaa"),
            new Cetrta.Prostor(4, 93, "ab"),
            new Cetrta.Prostor(4, 98, "ab"),
            new Cetrta.Prostor(1, 14, "abba"),
            new Cetrta.Prostor(4, 14, "ab"),
            new Cetrta.Prostor(2, 77, "aaaa"),
            new Cetrta.Prostor(1, 22, "ab"),
            new Cetrta.Prostor(1, 15, "aaaa"),
            new Cetrta.Prostor(4, 12, "bbbab"),
            new Cetrta.Prostor(3, 88, "aaaa"),
            new Cetrta.Prostor(4, 63, "aaaa"),
            new Cetrta.Prostor(1, 4, "abba"),
            new Cetrta.Prostor(2, 60, "bbab"),
            new Cetrta.Prostor(1, 18, "bbab"),
            new Cetrta.Prostor(4, 51, "aaaa"),
            new Cetrta.Prostor(3, 15, "aaaa"),
            new Cetrta.Prostor(5, 91, "bbab"),
            new Cetrta.Prostor(3, 27, "bbbab"),
            new Cetrta.Prostor(5, 45, "bbbab"),
            new Cetrta.Prostor(4, 49, "ab"),
            new Cetrta.Prostor(5, 50, "bbbab"),
            new Cetrta.Prostor(3, 97, "bbab"),
            new Cetrta.Prostor(2, 40, "bbab"),
            new Cetrta.Prostor(3, 94, "ab"),
            new Cetrta.Prostor(5, 78, "abba"),
            new Cetrta.Prostor(1, 33, "bbbab"),
            new Cetrta.Prostor(3, 93, "abba"),
            new Cetrta.Prostor(2, 73, "ab"),
            new Cetrta.Prostor(2, 17, "bbbab"),
            new Cetrta.Prostor(3, 65, "bbab"),
            new Cetrta.Prostor(3, 55, "aaaa"),
            new Cetrta.Prostor(2, 61, "bbbab"),
            new Cetrta.Prostor(5, 49, "bbbab"),
            new Cetrta.Prostor(3, 83, "bbbab"),
            new Cetrta.Prostor(2, 56, "abba"),
            new Cetrta.Prostor(1, 39, "ab"),
            new Cetrta.Prostor(4, 28, "abba"),
            new Cetrta.Prostor(4, 25, "abba"),
            new Cetrta.Prostor(2, 19, "aaaa"),
            new Cetrta.Prostor(1, 89, "aaaa"),
            new Cetrta.Prostor(1, 55, "bbbab"),
            new Cetrta.Prostor(2, 87, "ab")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
