
import java.util.*;

public class Test29 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(4, 100, "baaba"),
            new Cetrta.Prostor(1, 96, "abbaa"),
            new Cetrta.Prostor(5, 24, "aa"),
            new Cetrta.Prostor(5, 23, "baa"),
            new Cetrta.Prostor(2, 27, "aa"),
            new Cetrta.Prostor(4, 76, "aa"),
            new Cetrta.Prostor(3, 90, "babab"),
            new Cetrta.Prostor(2, 7, "baa"),
            new Cetrta.Prostor(2, 54, "baa"),
            new Cetrta.Prostor(2, 42, "aa"),
            new Cetrta.Prostor(5, 28, "babab"),
            new Cetrta.Prostor(2, 98, "baaba"),
            new Cetrta.Prostor(4, 32, "baa"),
            new Cetrta.Prostor(5, 38, "bbb"),
            new Cetrta.Prostor(3, 24, "aa"),
            new Cetrta.Prostor(4, 59, "baa"),
            new Cetrta.Prostor(3, 43, "aa"),
            new Cetrta.Prostor(5, 73, "aa"),
            new Cetrta.Prostor(5, 57, "aa"),
            new Cetrta.Prostor(5, 54, "abbaa"),
            new Cetrta.Prostor(4, 50, "abbaa"),
            new Cetrta.Prostor(1, 74, "abbaa"),
            new Cetrta.Prostor(1, 90, "baa"),
            new Cetrta.Prostor(5, 3, "babab"),
            new Cetrta.Prostor(4, 51, "aa"),
            new Cetrta.Prostor(3, 50, "aabab"),
            new Cetrta.Prostor(5, 13, "baaba"),
            new Cetrta.Prostor(4, 34, "aa"),
            new Cetrta.Prostor(1, 22, "abbaa"),
            new Cetrta.Prostor(5, 15, "bbb"),
            new Cetrta.Prostor(4, 88, "baa"),
            new Cetrta.Prostor(2, 1, "baa"),
            new Cetrta.Prostor(4, 46, "aa"),
            new Cetrta.Prostor(5, 95, "aa"),
            new Cetrta.Prostor(4, 85, "abbaa"),
            new Cetrta.Prostor(1, 93, "aabab"),
            new Cetrta.Prostor(1, 23, "bbb"),
            new Cetrta.Prostor(5, 4, "baa"),
            new Cetrta.Prostor(2, 16, "aa"),
            new Cetrta.Prostor(5, 85, "aba"),
            new Cetrta.Prostor(3, 76, "baa"),
            new Cetrta.Prostor(4, 39, "babab"),
            new Cetrta.Prostor(2, 94, "bbb"),
            new Cetrta.Prostor(3, 64, "aa"),
            new Cetrta.Prostor(2, 20, "abbaa"),
            new Cetrta.Prostor(4, 48, "baa"),
            new Cetrta.Prostor(5, 70, "baa"),
            new Cetrta.Prostor(5, 93, "baaba"),
            new Cetrta.Prostor(3, 66, "aba"),
            new Cetrta.Prostor(1, 88, "baa"),
            new Cetrta.Prostor(5, 99, "babab"),
            new Cetrta.Prostor(3, 22, "aabab"),
            new Cetrta.Prostor(5, 26, "baa"),
            new Cetrta.Prostor(5, 90, "baaba"),
            new Cetrta.Prostor(1, 30, "aabab"),
            new Cetrta.Prostor(4, 72, "babab"),
            new Cetrta.Prostor(5, 11, "aba"),
            new Cetrta.Prostor(5, 68, "baa"),
            new Cetrta.Prostor(5, 2, "aa"),
            new Cetrta.Prostor(3, 1, "baa"),
            new Cetrta.Prostor(1, 54, "bbb"),
            new Cetrta.Prostor(4, 18, "abbaa"),
            new Cetrta.Prostor(4, 99, "aba"),
            new Cetrta.Prostor(2, 73, "abbaa"),
            new Cetrta.Prostor(2, 48, "aabab"),
            new Cetrta.Prostor(5, 88, "babab"),
            new Cetrta.Prostor(4, 65, "abbaa"),
            new Cetrta.Prostor(2, 15, "aba"),
            new Cetrta.Prostor(2, 47, "baaba"),
            new Cetrta.Prostor(1, 1, "aabab"),
            new Cetrta.Prostor(2, 80, "aa"),
            new Cetrta.Prostor(1, 51, "babab"),
            new Cetrta.Prostor(3, 94, "aa"),
            new Cetrta.Prostor(1, 34, "baa"),
            new Cetrta.Prostor(5, 65, "aa"),
            new Cetrta.Prostor(1, 43, "bbb"),
            new Cetrta.Prostor(4, 11, "baa"),
            new Cetrta.Prostor(3, 54, "baa"),
            new Cetrta.Prostor(4, 45, "aa"),
            new Cetrta.Prostor(5, 80, "aa"),
            new Cetrta.Prostor(3, 92, "baa"),
            new Cetrta.Prostor(3, 65, "aba"),
            new Cetrta.Prostor(5, 67, "abbaa"),
            new Cetrta.Prostor(2, 55, "aa"),
            new Cetrta.Prostor(2, 31, "aa"),
            new Cetrta.Prostor(3, 82, "baaba"),
            new Cetrta.Prostor(4, 77, "aa"),
            new Cetrta.Prostor(3, 20, "baa"),
            new Cetrta.Prostor(1, 79, "aabab"),
            new Cetrta.Prostor(1, 7, "aa"),
            new Cetrta.Prostor(4, 80, "aa"),
            new Cetrta.Prostor(1, 98, "bbb"),
            new Cetrta.Prostor(3, 30, "aa"),
            new Cetrta.Prostor(1, 42, "aba"),
            new Cetrta.Prostor(2, 38, "aabab"),
            new Cetrta.Prostor(1, 65, "baaba"),
            new Cetrta.Prostor(4, 67, "bbb"),
            new Cetrta.Prostor(5, 81, "baa"),
            new Cetrta.Prostor(5, 35, "aa"),
            new Cetrta.Prostor(4, 61, "aabab")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
