
import java.util.*;

public class Test11 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 20, "ba"),
            new Cetrta.Prostor(3, 79, "abbab"),
            new Cetrta.Prostor(3, 12, "bba"),
            new Cetrta.Prostor(2, 10, "bbbbb"),
            new Cetrta.Prostor(1, 78, "aa"),
            new Cetrta.Prostor(2, 58, "abbab"),
            new Cetrta.Prostor(2, 47, "aa"),
            new Cetrta.Prostor(3, 29, "bb"),
            new Cetrta.Prostor(3, 88, "ba"),
            new Cetrta.Prostor(1, 93, "bb"),
            new Cetrta.Prostor(1, 38, "bba"),
            new Cetrta.Prostor(3, 86, "bb"),
            new Cetrta.Prostor(1, 87, "baabb"),
            new Cetrta.Prostor(1, 90, "bba"),
            new Cetrta.Prostor(3, 46, "bbbbb"),
            new Cetrta.Prostor(2, 42, "ba"),
            new Cetrta.Prostor(1, 61, "baabb"),
            new Cetrta.Prostor(3, 13, "aa"),
            new Cetrta.Prostor(3, 23, "ba"),
            new Cetrta.Prostor(1, 79, "aa"),
            new Cetrta.Prostor(2, 43, "baabb"),
            new Cetrta.Prostor(1, 25, "abbab"),
            new Cetrta.Prostor(3, 70, "bb"),
            new Cetrta.Prostor(2, 27, "baabb"),
            new Cetrta.Prostor(2, 23, "abbab"),
            new Cetrta.Prostor(2, 84, "bb"),
            new Cetrta.Prostor(2, 24, "ba"),
            new Cetrta.Prostor(2, 99, "ba"),
            new Cetrta.Prostor(2, 85, "bba"),
            new Cetrta.Prostor(2, 37, "aa"),
            new Cetrta.Prostor(2, 85, "baabb"),
            new Cetrta.Prostor(3, 28, "baabb"),
            new Cetrta.Prostor(1, 98, "baabb"),
            new Cetrta.Prostor(1, 60, "ba"),
            new Cetrta.Prostor(2, 54, "bb"),
            new Cetrta.Prostor(3, 74, "bba"),
            new Cetrta.Prostor(3, 13, "ba"),
            new Cetrta.Prostor(3, 93, "ba"),
            new Cetrta.Prostor(1, 69, "bba"),
            new Cetrta.Prostor(1, 61, "bbbbb"),
            new Cetrta.Prostor(3, 2, "aa"),
            new Cetrta.Prostor(3, 55, "bb"),
            new Cetrta.Prostor(1, 66, "abbab"),
            new Cetrta.Prostor(2, 90, "bb"),
            new Cetrta.Prostor(1, 45, "bbbbb"),
            new Cetrta.Prostor(2, 90, "bba"),
            new Cetrta.Prostor(1, 64, "bb"),
            new Cetrta.Prostor(1, 43, "bb"),
            new Cetrta.Prostor(2, 87, "baabb"),
            new Cetrta.Prostor(2, 82, "aa"),
            new Cetrta.Prostor(2, 87, "bb"),
            new Cetrta.Prostor(2, 74, "bb"),
            new Cetrta.Prostor(2, 44, "bba"),
            new Cetrta.Prostor(2, 11, "abbab"),
            new Cetrta.Prostor(2, 57, "bbbbb"),
            new Cetrta.Prostor(3, 12, "abbab"),
            new Cetrta.Prostor(2, 69, "bba"),
            new Cetrta.Prostor(1, 11, "bb"),
            new Cetrta.Prostor(3, 5, "ba"),
            new Cetrta.Prostor(2, 60, "ba"),
            new Cetrta.Prostor(1, 16, "bb"),
            new Cetrta.Prostor(2, 64, "ba"),
            new Cetrta.Prostor(3, 18, "abbab"),
            new Cetrta.Prostor(2, 7, "bb"),
            new Cetrta.Prostor(1, 31, "bb"),
            new Cetrta.Prostor(3, 8, "baabb"),
            new Cetrta.Prostor(3, 41, "abbab"),
            new Cetrta.Prostor(2, 53, "aa"),
            new Cetrta.Prostor(2, 8, "ba"),
            new Cetrta.Prostor(2, 35, "bb"),
            new Cetrta.Prostor(2, 51, "abbab"),
            new Cetrta.Prostor(2, 41, "bb"),
            new Cetrta.Prostor(1, 20, "bbbbb"),
            new Cetrta.Prostor(1, 11, "bba"),
            new Cetrta.Prostor(2, 38, "abbab"),
            new Cetrta.Prostor(1, 43, "bba"),
            new Cetrta.Prostor(2, 45, "bba"),
            new Cetrta.Prostor(2, 20, "bba"),
            new Cetrta.Prostor(3, 7, "bba"),
            new Cetrta.Prostor(3, 83, "bb"),
            new Cetrta.Prostor(2, 98, "bb"),
            new Cetrta.Prostor(3, 75, "ba"),
            new Cetrta.Prostor(2, 90, "bbbbb"),
            new Cetrta.Prostor(3, 35, "aa"),
            new Cetrta.Prostor(2, 87, "bb"),
            new Cetrta.Prostor(3, 36, "ba"),
            new Cetrta.Prostor(2, 10, "ba")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
