
import java.util.*;

public class Test01 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(6, 55, "aaa"),
            new Cetrta.Prostor(5, 7, "aaa"),
            new Cetrta.Prostor(4, 65, "aaabb"),
            new Cetrta.Prostor(6, 87, "aaabb"),
            new Cetrta.Prostor(1, 30, "aaa"),
            new Cetrta.Prostor(8, 56, "aaba"),
            new Cetrta.Prostor(2, 100, "aaba"),
            new Cetrta.Prostor(6, 67, "bab"),
            new Cetrta.Prostor(1, 100, "aaa"),
            new Cetrta.Prostor(5, 74, "aaabb"),
            new Cetrta.Prostor(7, 19, "aab"),
            new Cetrta.Prostor(1, 5, "baaa"),
            new Cetrta.Prostor(5, 3, "bab"),
            new Cetrta.Prostor(1, 61, "aaaa"),
            new Cetrta.Prostor(2, 5, "aab"),
            new Cetrta.Prostor(5, 76, "aaabb"),
            new Cetrta.Prostor(6, 6, "baaa"),
            new Cetrta.Prostor(2, 16, "aaa"),
            new Cetrta.Prostor(4, 79, "aab"),
            new Cetrta.Prostor(5, 67, "aab"),
            new Cetrta.Prostor(7, 92, "aaba"),
            new Cetrta.Prostor(8, 87, "aaaa"),
            new Cetrta.Prostor(3, 36, "aa"),
            new Cetrta.Prostor(7, 7, "aaa"),
            new Cetrta.Prostor(8, 52, "baaa"),
            new Cetrta.Prostor(4, 99, "aaa"),
            new Cetrta.Prostor(2, 31, "aaaa"),
            new Cetrta.Prostor(4, 95, "aaa"),
            new Cetrta.Prostor(4, 54, "aab"),
            new Cetrta.Prostor(4, 16, "baaa"),
            new Cetrta.Prostor(3, 37, "aab"),
            new Cetrta.Prostor(1, 68, "baaa"),
            new Cetrta.Prostor(3, 68, "baaa"),
            new Cetrta.Prostor(5, 12, "aaa"),
            new Cetrta.Prostor(6, 39, "aaaa"),
            new Cetrta.Prostor(8, 27, "aaba"),
            new Cetrta.Prostor(7, 53, "aaa"),
            new Cetrta.Prostor(5, 51, "bab"),
            new Cetrta.Prostor(5, 21, "bab"),
            new Cetrta.Prostor(5, 90, "aaa"),
            new Cetrta.Prostor(8, 36, "aaabb"),
            new Cetrta.Prostor(5, 42, "aab"),
            new Cetrta.Prostor(6, 5, "aab"),
            new Cetrta.Prostor(8, 29, "aaaa"),
            new Cetrta.Prostor(7, 31, "aaa"),
            new Cetrta.Prostor(8, 22, "aab"),
            new Cetrta.Prostor(2, 87, "aaba"),
            new Cetrta.Prostor(6, 93, "aab"),
            new Cetrta.Prostor(7, 27, "bab"),
            new Cetrta.Prostor(2, 75, "aaabb"),
            new Cetrta.Prostor(6, 59, "aaabb"),
            new Cetrta.Prostor(8, 29, "aaa"),
            new Cetrta.Prostor(8, 65, "aaabb"),
            new Cetrta.Prostor(6, 57, "aaba"),
            new Cetrta.Prostor(4, 8, "aaba"),
            new Cetrta.Prostor(8, 27, "aaaa"),
            new Cetrta.Prostor(7, 69, "bab"),
            new Cetrta.Prostor(1, 1, "bab"),
            new Cetrta.Prostor(1, 100, "bab"),
            new Cetrta.Prostor(4, 29, "aaa"),
            new Cetrta.Prostor(2, 90, "aab"),
            new Cetrta.Prostor(5, 88, "aaabb"),
            new Cetrta.Prostor(1, 15, "aaa"),
            new Cetrta.Prostor(5, 84, "aaaa"),
            new Cetrta.Prostor(3, 6, "aaaa"),
            new Cetrta.Prostor(3, 39, "aab"),
            new Cetrta.Prostor(8, 36, "aab"),
            new Cetrta.Prostor(6, 40, "aaa"),
            new Cetrta.Prostor(4, 72, "aaabb"),
            new Cetrta.Prostor(2, 38, "aaa"),
            new Cetrta.Prostor(8, 83, "bab"),
            new Cetrta.Prostor(4, 74, "bab"),
            new Cetrta.Prostor(1, 46, "aaaa"),
            new Cetrta.Prostor(4, 63, "baaa"),
            new Cetrta.Prostor(4, 88, "aab"),
            new Cetrta.Prostor(6, 60, "aaaa"),
            new Cetrta.Prostor(4, 42, "aab"),
            new Cetrta.Prostor(4, 57, "aa"),
            new Cetrta.Prostor(4, 16, "bab"),
            new Cetrta.Prostor(6, 26, "aaaa"),
            new Cetrta.Prostor(5, 49, "aaabb"),
            new Cetrta.Prostor(8, 97, "aaba"),
            new Cetrta.Prostor(7, 19, "aaba"),
            new Cetrta.Prostor(4, 6, "aaa"),
            new Cetrta.Prostor(7, 55, "baaa"),
            new Cetrta.Prostor(6, 81, "aaa")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
