
import java.util.*;

public class Test19 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(2, 97, "bbb"),
            new Cetrta.Prostor(1, 19, "aba"),
            new Cetrta.Prostor(2, 38, "bbb"),
            new Cetrta.Prostor(1, 39, "bbb"),
            new Cetrta.Prostor(1, 25, "aba"),
            new Cetrta.Prostor(1, 97, "aba"),
            new Cetrta.Prostor(1, 6, "bbb"),
            new Cetrta.Prostor(1, 37, "bbb"),
            new Cetrta.Prostor(1, 98, "bbb"),
            new Cetrta.Prostor(1, 17, "aba"),
            new Cetrta.Prostor(1, 2, "aba"),
            new Cetrta.Prostor(1, 93, "bbb"),
            new Cetrta.Prostor(1, 45, "aba"),
            new Cetrta.Prostor(2, 16, "bbb"),
            new Cetrta.Prostor(2, 12, "bbb"),
            new Cetrta.Prostor(2, 61, "bbb"),
            new Cetrta.Prostor(2, 43, "aba"),
            new Cetrta.Prostor(1, 83, "aba"),
            new Cetrta.Prostor(1, 95, "bbb"),
            new Cetrta.Prostor(1, 15, "bbb"),
            new Cetrta.Prostor(2, 2, "bbb"),
            new Cetrta.Prostor(2, 86, "aba"),
            new Cetrta.Prostor(1, 52, "aba"),
            new Cetrta.Prostor(2, 65, "bbb"),
            new Cetrta.Prostor(2, 26, "bbb"),
            new Cetrta.Prostor(2, 8, "aba"),
            new Cetrta.Prostor(1, 63, "bbb"),
            new Cetrta.Prostor(2, 93, "bbb"),
            new Cetrta.Prostor(1, 10, "aba"),
            new Cetrta.Prostor(1, 49, "aba"),
            new Cetrta.Prostor(2, 13, "aba"),
            new Cetrta.Prostor(1, 23, "bbb"),
            new Cetrta.Prostor(1, 61, "bbb"),
            new Cetrta.Prostor(1, 18, "aba"),
            new Cetrta.Prostor(1, 48, "aba"),
            new Cetrta.Prostor(2, 7, "bbb"),
            new Cetrta.Prostor(1, 59, "bbb"),
            new Cetrta.Prostor(1, 88, "aba"),
            new Cetrta.Prostor(2, 21, "bbb"),
            new Cetrta.Prostor(1, 68, "bbb"),
            new Cetrta.Prostor(2, 96, "bbb"),
            new Cetrta.Prostor(1, 56, "aba"),
            new Cetrta.Prostor(2, 9, "aba"),
            new Cetrta.Prostor(2, 68, "aba"),
            new Cetrta.Prostor(1, 58, "bbb"),
            new Cetrta.Prostor(1, 79, "bbb"),
            new Cetrta.Prostor(1, 72, "aba"),
            new Cetrta.Prostor(1, 46, "aba"),
            new Cetrta.Prostor(2, 50, "aba"),
            new Cetrta.Prostor(2, 87, "aba"),
            new Cetrta.Prostor(2, 76, "bbb"),
            new Cetrta.Prostor(2, 5, "bbb"),
            new Cetrta.Prostor(1, 11, "aba"),
            new Cetrta.Prostor(2, 36, "bbb"),
            new Cetrta.Prostor(1, 43, "bbb"),
            new Cetrta.Prostor(1, 60, "aba"),
            new Cetrta.Prostor(1, 41, "bbb"),
            new Cetrta.Prostor(1, 99, "bbb"),
            new Cetrta.Prostor(1, 91, "bbb"),
            new Cetrta.Prostor(1, 32, "aba"),
            new Cetrta.Prostor(1, 51, "aba"),
            new Cetrta.Prostor(2, 72, "aba"),
            new Cetrta.Prostor(2, 48, "aba"),
            new Cetrta.Prostor(2, 75, "bbb"),
            new Cetrta.Prostor(2, 55, "bbb"),
            new Cetrta.Prostor(2, 17, "bbb"),
            new Cetrta.Prostor(1, 64, "bbb"),
            new Cetrta.Prostor(1, 7, "bbb"),
            new Cetrta.Prostor(2, 20, "bbb"),
            new Cetrta.Prostor(2, 25, "aba"),
            new Cetrta.Prostor(2, 78, "bbb"),
            new Cetrta.Prostor(2, 44, "aba"),
            new Cetrta.Prostor(2, 80, "bbb"),
            new Cetrta.Prostor(1, 34, "bbb"),
            new Cetrta.Prostor(2, 10, "aba"),
            new Cetrta.Prostor(2, 98, "aba"),
            new Cetrta.Prostor(2, 57, "bbb"),
            new Cetrta.Prostor(2, 14, "aba"),
            new Cetrta.Prostor(2, 37, "aba"),
            new Cetrta.Prostor(1, 8, "bbb"),
            new Cetrta.Prostor(1, 57, "bbb"),
            new Cetrta.Prostor(1, 87, "bbb"),
            new Cetrta.Prostor(2, 40, "bbb"),
            new Cetrta.Prostor(1, 12, "aba"),
            new Cetrta.Prostor(1, 75, "aba"),
            new Cetrta.Prostor(2, 71, "aba"),
            new Cetrta.Prostor(1, 31, "bbb"),
            new Cetrta.Prostor(2, 79, "aba"),
            new Cetrta.Prostor(2, 30, "bbb"),
            new Cetrta.Prostor(1, 86, "bbb"),
            new Cetrta.Prostor(2, 19, "bbb"),
            new Cetrta.Prostor(2, 15, "aba"),
            new Cetrta.Prostor(1, 71, "bbb"),
            new Cetrta.Prostor(2, 35, "bbb"),
            new Cetrta.Prostor(1, 42, "aba"),
            new Cetrta.Prostor(2, 51, "bbb")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
